version: "3.7"

services:

    flask:
        build: ./flask
        # Naming a container gives it that hostname as well. So hostname for this container is "flask"
        container_name: flask
        restart: always
        environment: 
            - APP_NAME=MyFlaskApp
        expose: 
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
