version: '3.8'

services:
    go_auth:
        build: ./goAuth
        ports:
            - "5555:5555"
    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379" 
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root 
            MONGO_INITDB_ROOT_PASSWORD: password 
    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: password