version: '3'

services:    
    go_auth:
        build: ./goApp
        ports:
            - "8000:8000"
        networks:
          - mongo_cluster
    redis:
        image: redis
        ports:
            - "6379:6379" 
    
    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment: 
    #         ME_CONFIG_MONGODB_SERVER: mongos1
    #         ME_CONFIG_MONGODB_PORT: 27017
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: password
networks:
  mongo_cluster:
    external: 
      name: mongo_cluster