FROM python:3.7.9-alpine
ADD . /app
WORKDIR /app
EXPOSE 5000
COPY requirements.txt ./
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev 
RUN pip install psycopg2
RUN pip install -r requirements.txt
RUN export FLASK_APP=run.py
CMD [ "python", "run.py" ]